[project]
name = "kcd-mod-gfx-toolbox"
version = "0.1.0"
description = "CLI tool to compare two Scaleform .gfx files."
requires-python = ">= 3.11"
readme = "README.md"
dependencies = [
    "rich>=14.3.2",
]

[tool.ruff]
line-length = 120
